/*
 * This file is generated by jOOQ.
 */
package org.user_service.domain.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.user_service.domain.jooq.tables.AuthCode;
import org.user_service.domain.jooq.tables.records.AuthCodeRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthCodeRecord> PK_AUTH_CODE_EMAIL = Internal.createUniqueKey(AuthCode.AUTH_CODE, DSL.name("pk_auth_code_email"), new TableField[] { AuthCode.AUTH_CODE.EMAIL }, true);
}
