services:
  recommendation-service:
    build:
      context: ./microservice_reccomendations
      dockerfile: Dockerfile
    volumes:
      - .:/recommendation
    ports:
      - "5000:5000"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - postgres-user
      
  postgres-user:
    image: postgres
    environment:
      POSTGRES_DB: "user_info"
      POSTGRES_USER: "city-discover-user"
      POSTGRES_PASSWORD: "city-discover-2024"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5440:5432"

volumes:
  pgdata:
