/*
 * This file is generated by jOOQ.
 */
package org.user_service.domain.jooq.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import org.user_service.domain.jooq.tables.Token;


/**
 * User's token
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenRecord extends TableRecordImpl<TokenRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.token.user_id</code>. User id
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.token.user_id</code>. User id
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.token.refresh_token</code>. User refresh token
     */
    public void setRefreshToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.token.refresh_token</code>. User refresh token
     */
    public String getRefreshToken() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Token.TOKEN.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return Token.TOKEN.REFRESH_TOKEN;
    }

    @Override
    public UUID component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getRefreshToken();
    }

    @Override
    public UUID value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getRefreshToken();
    }

    @Override
    public TokenRecord value1(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public TokenRecord value2(String value) {
        setRefreshToken(value);
        return this;
    }

    @Override
    public TokenRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(UUID userId, String refreshToken) {
        super(Token.TOKEN);

        setUserId(userId);
        setRefreshToken(refreshToken);
        resetChangedOnNotNull();
    }
}
