/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import java.util.Arrays;
import java.util.List;

import org.city_discover.domain.jooq.tables.Kitty;
import org.city_discover.domain.jooq.tables.Owner;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Kitties
     */
    public final Kitty KITTY = Kitty.KITTY;

    /**
     * Owners
     */
    public final Owner OWNER = Owner.OWNER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Kitty.KITTY,
            Owner.OWNER
        );
    }
}
