/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import org.city_discover.domain.jooq.tables.Kitty;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Kitties
     */
    public static final Kitty KITTY = Kitty.KITTY;
}
