server:
  port: ${PORT_TO_EXPOSE:8050}
  forward-headers-strategy: framework
  servlet:
    context-path: "/user-service"

spring:
  liquibase:
    change-log: classpath:db.changelog/master.xml
    enabled: true
  datasource:
    url: "jdbc:postgresql://postgres-user:5432/user_info"
    username: city-discover-user
    password: city-discover-2024
    hikari:
      driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

  data:
    web:
      pageable:
        max-page-size: 10000
  application:
    name: "user-service"

  mail:
    host: smtp.yandex.ru
    port: 465
    sender:
      username: "citydiscover"
      email: "citydiscover@yandex.ru"
      password: "..."
    protocol: "smtp"

jwt:
  secret: "uR2djMIlRYULTTvgMdQMFkil5Ecg3qauWYfVbw0jQyTYx0a1Lm2bW9"
  admin-secret: "gVc85nCtlEWatZglm9kDNGOD"

recommendation:
  host: recommendation-service
  port: 5000