/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import java.util.Arrays;
import java.util.List;

import org.city_discover.domain.jooq.tables.AuthCode;
import org.city_discover.domain.jooq.tables.Subscription;
import org.city_discover.domain.jooq.tables.Token;
import org.city_discover.domain.jooq.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * User's disposable codes for auth
     */
    public final AuthCode AUTH_CODE = AuthCode.AUTH_CODE;

    /**
     * Subscriptions
     */
    public final Subscription SUBSCRIPTION = Subscription.SUBSCRIPTION;

    /**
     * User's token
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * User's info
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthCode.AUTH_CODE,
            Subscription.SUBSCRIPTION,
            Token.TOKEN,
            User.USER
        );
    }
}
