/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import org.city_discover.domain.jooq.tables.AuthCode;
import org.city_discover.domain.jooq.tables.Subscription;
import org.city_discover.domain.jooq.tables.Token;
import org.city_discover.domain.jooq.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * User's disposable codes for auth
     */
    public static final AuthCode AUTH_CODE = AuthCode.AUTH_CODE;

    /**
     * Subscriptions
     */
    public static final Subscription SUBSCRIPTION = Subscription.SUBSCRIPTION;

    /**
     * User's token
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * User's info
     */
    public static final User USER = User.USER;
}
