/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import org.city_discover.domain.jooq.tables.Place;
import org.city_discover.domain.jooq.tables.records.PlaceRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlaceRecord> PK_PLACE_UUID = Internal.createUniqueKey(Place.PLACE, DSL.name("pk_place_uuid"), new TableField[] { Place.PLACE.ID }, true);
}
