/*
 * This file is generated by jOOQ.
 */
package org.city_discover.domain.jooq;


import org.city_discover.domain.jooq.tables.Place;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Places
     */
    public static final Place PLACE = Place.PLACE;
}
