server:
  port: ${PORT_TO_EXPOSE:8050}
  forward-headers-strategy: framework
  servlet:
    context-path: "/game-service"

spring:
  liquibase:
    change-log: classpath:db.changelog/master.xml
    enabled: true
  datasource:
    url: "jdbc:postgresql://postgres-game:5432/game_info"
    username: "city-discover-user"
    password: "city-discover-2024"
    hikari:
      driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

  data:
    web:
      pageable:
        max-page-size: 10000
  application:
    name: "game-service"

jwt:
  secret: "uR2djMIlRYULTTvgMdQMFkil5Ecg3qauWYfVbw0jQyTYx0a1Lm2bW9"
  admin-secret: "gVc85nCtlEWatZglm9kDNGOD"

minio:
  minio-url: "http://minio:9000"
  base-folder: "kitties"
  bucket-name: "city-discover"
  login: "minio_city"
  password: "minio_city_2024"